// <auto-generated>
// Rewired Constants
// This list was generated on 28/11/2023 12:31:46
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal")]
        public const int MOVE_HORIZONTAL = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical")]
        public const int MOVE_VERTICAL = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "A")]
        public const int ACTION1 = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "X")]
        public const int ACTION2 = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "B")]
        public const int ACTION3 = 4;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Y")]
        public const int ACTION4 = 5;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "JS R X")]
        public const int AXISX = 6;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "JS R Y")]
        public const int AXISY = 7;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LT")]
        public const int LT = 12;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "RT")]
        public const int RT = 13;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LB")]
        public const int LB = 14;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "RB")]
        public const int RB = 15;
        
        // Assignment
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Assignment", friendlyName = "JoinGame")]
        public const int JOINGAME = 8;
        
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "MoveMenuHorizontal")]
        public const int MOVEMENUHORIZONTAL = 9;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "MoveMenuVertical")]
        public const int MOVEMENUVERTICAL = 16;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Accept")]
        public const int ACCEPT = 10;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Return")]
        public const int RETURN = 11;
        
    }
    public static partial class Category {
        public const int DEFAULT = 0;
        
        public const int ASSIGNMENT = 1;
        
        public const int UI = 2;
        
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int DEFAULT = 0;
            
        }
        public static partial class Keyboard {
            public const int DEFAULT = 0;
            
            public const int PLAYER1 = 1;
            
            public const int PLAYER2 = 2;
            
            public const int PLAYER3 = 3;
            
        }
        public static partial class Mouse {
            public const int DEFAULT = 0;
            
        }
        public static partial class CustomController {
            public const int DEFAULT = 0;
            
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1KB")]
        public const int PLAYER1KB = 0;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1JS")]
        public const int PLAYER1JS = 1;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2KB")]
        public const int PLAYER2KB = 2;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2JS")]
        public const int PLAYER2JS = 3;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3KB")]
        public const int PLAYER3KB = 4;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3JS")]
        public const int PLAYER3JS = 5;
        
    }
    public static partial class CustomController {
    }
}
